apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: otel-file-export
  namespace: otel-demo26
spec:
  accessModes: [ ReadWriteOnce ]
  storageClassName: standard
  resources:
    requests:
      storage: 10Gi
